# Generated by Django 4.0.6 on 2022-07-15 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=1000)),
                ('lname', models.CharField(max_length=1000)),
                ('grade', models.CharField(max_length=5)),
                ('section', models.CharField(max_length=5)),
                ('hname', models.CharField(max_length=1000)),
                ('treatment', models.CharField(max_length=1000000)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
