# Generated by Django 4.0.6 on 2022-07-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infirmaryWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='purpose',
            field=models.CharField(default='General', max_length=1000),
        ),
        migrations.AlterField(
            model_name='record',
            name='treatment',
            field=models.CharField(default='General', max_length=1000000),
        ),
    ]
